### ISSUE TITLE
Add redirect for Press Pack: Libero Publisher demo launch 

### ISSUE THREAD

**Issue by ELPacker** [elifesciences/journal-formula#119]
Please could you set up a redirect, so that the following URL – https://elifesciences.org/for-the-press/d5b3c1bf/elife-introduces-first-demonstration-of-the-open-source-publishing-platform-libero-publisher – directs users to https://libero.pub/products/libero-publisher/ instead? @Maelplaine (I've chatted informally to Nathan about this)

**Comment by nlisgo** [comment]
I have a PR for the redirects: https://github.com/elifesciences/journal-formula/pull/120

Once the redirects are in place then I will unpublish the content.

**Comment by nlisgo** [comment]
@ELPacker can you confirm that the redirects are in place now?

**Comment by nlisgo** [comment]
I have prepared a PR to Journal CMS to unpublish the press package but will await confirmation from @ELPacker that the redirects are in place.

See: https://github.com/elifesciences/journal-cms/pull/540

**Comment by ELPacker** [comment]
Hi @nlisgo – I can confirm that the redirects are now in place. Many thanks!
